# Generated by Django 4.2.29 on 2026-03-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0005_user_twofa_enabled_user_twofa_recovery_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('receptionist', 'Receptionist')], default='receptionist', max_length=20),
        ),
    ]
